# =============================================================================
# Composite Action: Setup comfy-test environment
# =============================================================================
# This action sets up everything needed to run comfy-test:
# - Python
# - uv (fast pip replacement)
# - Playwright browser (CACHED to save ~2-3 min per run)
# - comfy-test itself
#
# Usage in workflow:
#   - uses: ./.comfy-test-src/.github/actions/setup
#     with:
#       python-version: "3.11"
# =============================================================================

name: Setup comfy-test environment
description: Sets up Python, Playwright (cached), and comfy-test

inputs:
  python-version:
    description: "Python version to use"
    required: true
  comfy-test-path:
    description: "Path to comfy-test checkout"
    default: "./.comfy-test-src"

runs:
  using: composite
  steps:
    # -------------------------------------------------------------------------
    # Step 1: Try to restore Playwright cache
    # -------------------------------------------------------------------------
    - name: Restore Playwright cache
      id: playwright-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: playwright-${{ runner.os }}-chromium

    # -------------------------------------------------------------------------
    # Step 2: Setup Python
    # -------------------------------------------------------------------------
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # -------------------------------------------------------------------------
    # Step 3: Install uv (fast pip replacement)
    # -------------------------------------------------------------------------
    - name: Install uv
      shell: bash
      run: pip install uv

    # -------------------------------------------------------------------------
    # Step 4: Install comfy-test
    # -------------------------------------------------------------------------
    - name: Install comfy-test
      shell: bash
      run: pip install "${{ inputs.comfy-test-path }}[screenshot]"

    # -------------------------------------------------------------------------
    # Step 5: Install Playwright browser
    # -------------------------------------------------------------------------
    - name: Install Playwright
      shell: bash
      run: |
        playwright install chromium
        playwright install-deps chromium || true

    # -------------------------------------------------------------------------
    # Step 6: IMMEDIATELY save cache after download (if it was a miss)
    # -------------------------------------------------------------------------
    - name: Save Playwright cache
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: playwright-${{ runner.os }}-chromium
